package:
  name: postgresql
  version: 9.3.5

source:
  fn: postgresql-9.3.5.tar.bz2
  url: http://ftp.postgresql.org/pub/source/v9.3.5/postgresql-9.3.5.tar.bz2

build:
  number: 0

requirements:
  build:
    - python
    - openssl
    - readline
    - libxml2   [not osx]
    - libxslt   [not osx]
    - zlib
    - system    [linux]
  run:
    - python
    - openssl
    - readline
    - libxml2   [not osx]
    - libxslt   [not osx]
    - zlib
    - system    [linux]

test:
  commands:
    - initdb --help
    - postgres --help
    - createdb --help
    - psql --help

about:
  home: http://www.postgresql.org
  license: MIT
