package:
  name: mysql
  version: 5.6.20

source:
  fn: mysql-5.6.20.tar.gz
  url: http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.20.tar.gz
  sha1: 10f9ed2bbf3fbf227b799f1c7af3a0c7f7cf4d95

requirements:    
   build:
    - python
    - cmake       
    - system [linux]                                                                                                                                                                

build:
  number: 0

about:
  home: http://dev.mysql.com/doc/refman/5.6/en/
  license: GPL
