package:
  name: pyhive
  version: !!str 0.1.3

source:
  git_url: https://github.com/dropbox/PyHive.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - sasl
    - thrift
    - sqlalchemy

test:
  # Python imports
  imports:
    - pyhive

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dropbox/PyHive
  license: Apache Software License
  summary: 'Python interface to Hive'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
