package:
    name: sqlite3
    version: 3.8.6

source:
    fn: sqlite-shell-win32-x86-3080600.zip
    url: http://www.sqlite.org/2014/sqlite-shell-win32-x86-3080600.zip
    sha1: e25f75ed380d9f7458fd024db01a946a65852e8c 

build:
    number: 0

test:
    commands:
        - sqlite3.exe --version

about:
    home: http://www.sqlite.org/copyright.html 
    license: Public Domain
