package:
  name: impyla
  version: !!str 0.8.1

source:
  git_url: git@github.com:cloudera/impyla.git
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - impyla = impyla:main
    #
    # Would create an entry point called impyla that calls impyla.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - thrift

  run:
    - python
    - thrift

test:
  # Python imports
  imports:
    - impala

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cloudera/impyla
  license: Apache License, Version 2.0
  summary: 'Python client for the Impala distributed query engine'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
